import Nav from "./Nav";
import Footer from "./Footer";
import type { Translations } from "@/lib/i18n/types";

interface LegalLayoutProps {
  t: Translations;
  locale: string;
  title: string;
  lastUpdated: string;
  content: string;
}

export default function LegalLayout({ t, locale, title, lastUpdated, content }: LegalLayoutProps) {
  return (
    <>
      <Nav t={t.nav} />
      <main className="max-w-[780px] mx-auto px-5 md:px-10 py-12 md:py-20">
        <div className="mb-8">
          <h1 className="text-[32px] md:text-[40px] font-extrabold tracking-[-0.03em] leading-tight mb-2">
            {title}
          </h1>
          <p className="text-[13px] text-[var(--color-neutral-500)] font-mono">
            {lastUpdated}
          </p>
        </div>

        <div
          className="legal-content"
          dangerouslySetInnerHTML={{ __html: content }}
        />

        <div className="mt-12 pt-6 border-t border-[var(--color-neutral-200)] text-[12px] text-[var(--color-neutral-400)] font-mono">
          Generated by{" "}
          <a
            href="https://termly.io"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-[var(--color-text)] transition-colors"
          >
            Termly
          </a>
        </div>
      </main>
      <Footer t={t.footer} locale={locale} />
    </>
  );
}
